# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog-yc  
url: http://yc247796047.github.io
feed: /atom.xml
author_info: <a href="http://yc247796047.github.io/">yangchun</a>

myblog:
  gavatar: images/2.jpg
  gpname: yangchun
  github: https://github.com/yc247796047
  email: mailto:247796047@qq.com
  linkedin: https://www.linkedin.com/in/yang-chun-b36a69163/
  coverimgs: []
  postbgimg: []


